name: Kwiki-Weather
version: 0.03
abstract: Weather button and WAFL for your Kwiki
author: Ian Langworth <langworth.com>
license: perl
distribution_type: module
requires:
  perl: 5.6.1
  Kwiki: 0.32
  Kwiki::Zipcode: 0.11
  Geo::Weather: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.33
